# Generated by Django 5.2.3 on 2025-07-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(verbose_name='Twitch User ID')),
                ('login', models.CharField(verbose_name='User Name')),
                ('display_name', models.CharField(verbose_name='User Display Name')),
                ('type', models.CharField(verbose_name='User type')),
                ('broadcaster_type', models.CharField(verbose_name='Broadcaster Type')),
                ('channel_description', models.CharField(verbose_name='Channel Description')),
                ('profile_image_url', models.CharField(verbose_name='Profile Image URL')),
                ('email', models.CharField(verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_location', models.CharField(max_length=50, verbose_name='Media file path for assets')),
                ('tts_enabled', models.BooleanField(verbose_name='TTS enabled')),
                ('tts_trigger', models.CharField(choices=[('message', 'Chat Message'), ('cheer', 'Bits Used'), ('sub', 'Subscription, Renewal, or Gift')], verbose_name='TTS message trigger')),
                ('tts_cost', models.IntegerField(verbose_name='TTS relevant trigger cost')),
                ('tts_model_enabled', models.BooleanField(verbose_name='TTS speaker model enabled')),
                ('sound_enabled', models.BooleanField(verbose_name='Sound Bite enabled')),
                ('sound_trigger', models.CharField(choices=[('message', 'Chat Message'), ('cheer', 'Bits Used'), ('sub', 'Subscription, Renewal, or Gift')], verbose_name='Sound Bite message trigger')),
                ('sound_cost', models.IntegerField(verbose_name='Sound Bite relevant trigger cost')),
                ('lute_enabled', models.BooleanField(verbose_name='LuteBoi enabled')),
                ('lute_trigger', models.CharField(choices=[('message', 'Chat Message'), ('cheer', 'Bits Used'), ('sub', 'Subscription, Renewal, or Gift')], verbose_name='LuteBoi message trigger')),
                ('lute_cost', models.IntegerField(verbose_name='LuteBoi relevant trigger cost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='Channel Settings')),
            ],
        ),
        migrations.CreateModel(
            name='UserModeratorRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_moderator', to='core.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_owner', to='core.user')),
            ],
            options={
                'unique_together': {('user', 'moderator')},
            },
        ),
    ]
