# Generated by Django 5.2.3 on 2025-06-27 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(verbose_name='Twitch User ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Twitch User/Channel Name')),
                ('profile_name', models.CharField(max_length=50, verbose_name='Twitch User Display Name')),
                ('profile_url', models.CharField(max_length=200, verbose_name='Twitch Profile URL')),
                ('channel_id', models.CharField(verbose_name='Twitch Channel ID')),
                ('channel_description', models.CharField(max_length=300, verbose_name='Channel description')),
                ('last_live', models.DateField(verbose_name='Last Date Channel was Live')),
                ('last_authentication', models.DateField(verbose_name='Last Date Authenticated')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_location', models.CharField(max_length=50, verbose_name='Media file path for assets')),
                ('tts_enabled', models.BooleanField(verbose_name='TTS enabled')),
                ('tts_trigger', models.CharField(choices=[('message', 'Chat Message'), ('cheer', 'Bits Used'), ('sub', 'Subscription, Renewal, or Gift')], verbose_name='TTS message trigger')),
                ('tts_cost', models.IntegerField(verbose_name='TTS relevant trigger cost')),
                ('tts_model_enabled', models.BooleanField(verbose_name='TTS speaker model enabled')),
                ('sound_enabled', models.BooleanField(verbose_name='Sound Bite enabled')),
                ('sound_trigger', models.CharField(choices=[('message', 'Chat Message'), ('cheer', 'Bits Used'), ('sub', 'Subscription, Renewal, or Gift')], verbose_name='Sound Bite message trigger')),
                ('sound_cost', models.IntegerField(verbose_name='Sound Bite relevant trigger cost')),
                ('lute_enabled', models.BooleanField(verbose_name='LuteBoi enabled')),
                ('lute_trigger', models.CharField(choices=[('message', 'Chat Message'), ('cheer', 'Bits Used'), ('sub', 'Subscription, Renewal, or Gift')], verbose_name='LuteBoi message trigger')),
                ('lute_cost', models.IntegerField(verbose_name='LuteBoi relevant trigger cost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='Channel Settings')),
            ],
        ),
        migrations.CreateModel(
            name='UserModeratorRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_moderator', to='core.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_owner', to='core.user')),
            ],
            options={
                'unique_together': {('user', 'moderator')},
            },
        ),
    ]
