# Generated by Django 5.2.3 on 2025-07-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh',
            field=models.CharField(default='', verbose_name='User Auth Refresh'),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='', verbose_name='User Auth Token'),
        ),
    ]
