# Generated by Django 5.2.3 on 2025-07-13 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_refresh_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='scope',
        ),
        migrations.AddField(
            model_name='trigger',
            name='event',
            field=models.CharField(default=True, unique=True, verbose_name='Required Event Type'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='trigger_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trigger', to_field='event', verbose_name='Trigger Event Type'),
        ),
    ]
