# Generated by Django 5.2.3 on 2025-07-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_trigger_scope_trigger_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='event',
            field=models.CharField(unique=True, verbose_name='Event Type'),
        ),
    ]
