name: ttsboi

services:
  # Reverse Proxy
  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/staticfiles

  # Tunnel
  ngrok:
    image: ngrok/ngrok
    command: http host.docker.internal:80 --url ruling-walrus-main.ngrok-free.app
    env_file:
      - ./.config/ngrok.env
    depends_on:
      - nginx

  # Broker
  redis:
    image: redis:8.0-alpine
    ports:
      - 6379:6379
    restart: always

  redis_insight:
    image: redis/redisinsight:2.68
    ports:
      - 5540:5540
    depends_on:
      - redis
    restart: always
  
  # Main Django instance
  portal:
    build:
      context: ./portal/
    ports:
      - 1500:1500
      - 1501:1501
    volumes:
      - ./portal/:/usr/src/app/
      - static_files:/usr/src/app/staticfiles
    env_file:
      - ./.config/.env

  # Celery worker
  generator:
    build:
      context: ./generator/
      dockerfile: Dockerfile
    command: celery -A generator worker -l INFO -Q generator_queue
    volumes:
      - ./generator/:/usr/src/app/
    depends_on:
      - portal
      - redis

volumes:
  static_files:
