name: ttsboi

services:
  # Reverse Proxy
  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/staticfiles

  # Tunnel
  ngrok:
    image: ngrok/ngrok
    command: http host.docker.internal:80
    env_file:
      - ./.config/ngrok.env
    depends_on:
      - nginx

  # Broker
  redis:
    image: redis:8.0-alpine
    expose:
      - 6379
    restart: always

  redis_insight:
    image: redis/redisinsight:2.68
    expose:
      - 5540
    depends_on:
      - redis
    restart: always
  
  # Main Django instance
  portal:
    build:
      context: ./portal/
    expose:
      - 1500
      - 1501
    volumes:
      - ./portal/:/usr/src/app/
      - static_files:/usr/src/app/staticfiles
      - tmp_files:/user/src/app/tmpfiles
    env_file:
      - ./.config/.env

  # Celery worker
  generator:
    build:
      context: ./portal/
    entrypoint: celery -A core worker -c 4 -l INFO -Q generator_queue
    volumes:
      - ./portal/:/usr/src/app/
      - tmp_files:/user/src/app/tmpfiles
    env_file:
      - ./.config/.env
    depends_on:
      - portal
      - redis

volumes:
  static_files:
  tmp_files:
